### PR TITLE
Added rgb8 encoding support

### PR DESCRIPTION
**Pull request by kmalhan**
In this pull request, I have added rgb8 support. Since I have to modify multiple files to add the feature, I have divided into 4 different commits. 

I made each commit as simple as possible, and described the intention of code change. Please review and let me know if additional updates are required.

As I mentioned previously, the changes are tested with Basler daA1600-60uc.

### CODE REVIEW

**Comment by kmalhan** [comment]
@NikolasE , Could you provide the feedback?

**Comment by marc-up** [comment]
Hey kmalhan,

thanks for your contribution. I've been on vacation - sorry for my late reply. 
I just went briefly through your PR and recognized that some parts may not work for all three types of cameras. Unfortunately we don't have GigE-color camera up to now, but I will ask for one, test your code and give you feedback (hopefully) soon.

**Comment by marc-up** [comment]
News from our side! The cameras arrived and I could test your code. But changes have to be made in order to support all types of USB 3.0 cameras (e.g. enum-names are different). Currently e.g. the acA4600-10uc is not supported and the node crashes with:
`[/pylon_camera_node ERROR 1474905777.272208365]: Error applying image encoding to USB cameras: Failed to write enumeration value. Enum entry is not writable
`
But I will have a look at this and provide a fix.

**Comment by marc-up** [comment]
Finally. Sorry for the delay. Could you give me feedback if this works like you expect?

**Comment by kmalhan** [comment]
Thank you very much for further developing the code and merging changes! It works with Basler daA1600-60uc as I expected.

**Pull request merged**
