### PR TITLE
Added YUV422(color) encoding to basler/ros lookups

### PR DESCRIPTION
**Pull request by shaun-edwards**

### CODE REVIEW

**Comment by marc-up** [comment]
What camera are you using? I couldn't find one here that supports the YUV422Packed encoding. I would like to merge, but I'm not sure if the brightness search is still working with above encoding because its designed for 8Bit pixel depth. Does it work with your camera?

**Comment by shaun-edwards** [comment]
We are usging the [acA1600-20gc](http://www.baslerweb.com/en/products/cameras/area-scan-cameras/ace/aca1600-20gc).  The brightness search seems to fail often, but it gets close enough for my work.  We are in a poorly lit environment, so I just attributed the failures to that.  Maybe the pixel depth is the reason?  Is there a way you would recommend to debug the failures?

On a side note, we are having trouble with the cameras loosing connection (at the pylon method call).  Do you recommend a different camera?

**Comment by marc-up** [comment]
As far as I can see, your cam provides only 12 bit pixel depth. The brightness search does fail because of that reason. Regarding your 'loosing connection' problem: Does this appear in case you grab images using the PylonViewerApp? Did you try out to set the mtu size of your network card to e.g. 9000? Contacting the support of Basler is also a good idea, they always do their best to help you out.

**Comment by shaun-edwards** [comment]
@marceldebout, thanks for the feedback.  I will reach out to Basler regarding the our connection issues.  We are running multiple cameras, so that could also be the issue.

Do you have any suggestions on how to support 12 bit pixel depth?  Do you think it's possible to still incorporate these changes if I also updated the brightness search?

**Comment by marc-up** [comment]
@shaun-edwards You're welcome! So in my opinion there are two open issues. One is the support of 12bit pixel depth and the other one is the automatic setup in case multiple gige cameras are connected. I think I will open two issues and we can discuss possible solutions and how extensive it would be to implement them in the separated threads. Above support of the YUV422 encoding is a minor task, but requires the 12 bit pixel depth support first. Anyway, is changing the camera and making use of an 8 bit camera an option for you? Illuminating the scene is furthermore a good idea to stabilize image acquisition...

**Comment by shaun-edwards** [comment]
>One is the support of 12bit pixel depth...

We could switch to 8 bit cameras, 12 bit was just what we had in the lab.  If it's very difficult to support 12 bit, then we would switch.  I'll follow your advice on this.

>  the other one is the automatic setup in case multiple gige cameras are connected...

Do you think the driver issues we are seeing are due to multiple camera connections/nodes?  Shouldn't the pylon software be able multiple instances?  I've reached out to Bazler on this, but any insight you have is much appreciated.

**Comment by shaun-edwards** [comment]
Closing as supporting 12 bit will require more changes than just image format.

**Pull request closed without merging**
